bin/aegir-systemctl-status: fix regexp for Standalone

diff --git a/bin/aegir-systemctl-status b/bin/aegir-systemctl-status
--- a/bin/aegir-systemctl-status
+++ b/bin/aegir-systemctl-status
@@ -5,11 +5,10 @@
 service=$1
 
 # Validate that the service looks like a cron
-echo $service | grep -q -E "^(d7|d8|d9|wp)(civi|drupal|core)cron"
-
-if [ $? != 0 ]; then
-  echo "Error: Invalid service format"
+re='^(d7|wp)?(civi|drupal|core)cron_[[:alnum:]]+$'
+if ! [[ $service =~ $re ]]; then
+  echo "Error: Invalid service format $service"
   exit 1
 fi
 
-systemctl status -- "$service" 2>&1
+systemctl status -- "$service.service" 2>&1
